language: node_js
node_js:
  - "8"
  - "10"
addons:
  apt:
    update: true
    packages:
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev
script:
  - npm run test
after_success:
  - npm run-script coveralls
cache:
  directories:
    - node-modules
